import { Project } from '../src/types';

export const RESPECTED_COMPANY_PROJECTS: Project[] = [
  {
    id: 'proj_google_cloud_observability',
    title: 'Distributed Cloud Observability & OpenTelemetry Tracing Engine',
    domain: 'Cloud Computing',
    industryCategory: 'Cloud Infrastructure',
    companyName: 'Google',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks (36 hours)',
    description:
      'Architect a distributed telemetry collector that aggregates OpenTelemetry spans, metrics, and logs across microservices with automated Prometheus alerting and distributed tracing visualization.',
    requiredSkills: ['Go', 'Kubernetes', 'OpenTelemetry', 'Prometheus', 'Distributed Systems'],
    recommendedCompanies: ['Google', 'Microsoft', 'Netflix', 'Amazon'],
    softwareRequirements: ['Go 1.22+', 'Docker', 'Minikube or Kind', 'Grafana & Prometheus', 'Jaeger'],
    expectedOutput:
      'A containerized microservices suite instrumented with OpenTelemetry sending live traces to Jaeger and metrics to Prometheus with zero packet drop under load.',
    descriptiveQuestionPrompt:
      'Explain your distributed tracing propagation strategy across synchronous HTTP and asynchronous message queues. How do you prevent telemetry overhead from impacting core service latency?',
    stages: [
      {
        id: 'gco_s1',
        stageNumber: 1,
        title: 'OpenTelemetry Context Propagation & Architecture',
        shortDescription: 'Master W3C Trace Context and distributed trace header injection across network boundaries.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_coursera_gcp_arch',
            title: 'Architecting with Google Cloud Platform Design and Process',
            provider: 'Coursera',
            topic: 'Microservices Reliability & SRE Principles',
            skillCovered: 'Cloud Computing',
            level: 'Advanced',
            estimatedDuration: '8 hours',
            url: 'https://www.coursera.org/learn/gcp-architecture-design-process',
            isOfficial: true,
          },
          {
            id: 'res_nptel_dist_sys',
            title: 'Distributed Systems & Cloud Computing by IIT Madras',
            provider: 'NPTEL',
            topic: 'Distributed Tracing & Clock Synchronization',
            skillCovered: 'Distributed Systems',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/106/106/106106168/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_gco_1_1',
            question: 'What is the primary role of the `traceparent` header in the W3C Trace Context specification?',
            options: [
              'It encrypts the payload using TLS 1.3 certificates',
              'It carries the 4-part identifier: version, trace ID, parent span ID, and trace flags across HTTP boundaries',
              'It determines the round-robin load balancing weight of the container',
              'It stores user session cookies for single sign-on authentication',
            ],
            correctAnswer: 1,
            explanation:
              'The W3C traceparent header propagates the standard 16-byte trace-id and 8-byte parent-id so downstream services can link child spans to the parent root request.',
            topic: 'Distributed Tracing',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'gco_s2',
        stageNumber: 2,
        title: 'Guided Task: Instrument HTTP Client with Span Exporter',
        shortDescription: 'Configure an OpenTelemetry Go tracer and verify live span ingestion in Jaeger.',
        type: 'guided_task',
        xpReward: 250,
        task: {
          id: 'task_gco_instrument',
          title: 'Implement OpenTelemetry Tracer Middleware in Go',
          objective: 'Inject trace context into outbound calls and extract parent spans in inbound handlers.',
          explanation:
            'Every request must instantiate a child span, record latency, capture HTTP response codes, and export telemetry to OTLP collector.',
          requiredSkills: ['Go', 'OpenTelemetry', 'Docker'],
          requiredTools: ['Go Compiler', 'Docker Compose', 'Jaeger UI'],
          instructions: [
            'Initialize an OTLP HTTP/gRPC exporter connecting to localhost:4317',
            'Register a global TracerProvider with BatchSpanProcessor',
            'Wrap HTTP router handlers with otelhttp middleware',
            'Trigger 10 sample requests and inspect waterfall trace views in Jaeger UI',
          ],
          expectedOutput:
            'A verified Jaeger waterfall trace displaying root span, database query child span, and exact microsecond timing.',
          checklist: [
            'Tracer provider initialized with service name',
            'Trace context propagated across network hops',
            'Jaeger collector receiving valid OTLP packets',
          ],
          difficulty: 'Intermediate',
          xpReward: 250,
        },
        mcqs: [
          {
            id: 'mcq_gco_2_1',
            question: 'Why is BatchSpanProcessor preferred over SimpleSpanProcessor in production telemetry?',
            options: [
              'SimpleSpanProcessor crashes when memory usage exceeds 10MB',
              'BatchSpanProcessor buffers spans asynchronously, preventing network I/O blocking on every single trace',
              'BatchSpanProcessor automatically creates database tables in PostgreSQL',
              'SimpleSpanProcessor cannot serialize JSON payloads',
            ],
            correctAnswer: 1,
            explanation:
              'SimpleSpanProcessor exports synchronously on each span completion, adding severe network latency to customer requests. BatchSpanProcessor batches spans in background memory.',
            topic: 'Observability',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'gco_s3',
        stageNumber: 3,
        title: 'Core Build: Metrics Pipeline & Chaos Failure Injection',
        shortDescription: 'Deploy Prometheus RED metrics (Rate, Errors, Duration) and simulate network packet delays.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_gco_metrics',
          title: 'Build Prometheus RED Dashboard & Alerting Rules',
          objective: 'Export histogram metrics for request duration and configure alerts for P99 latency breaches.',
          explanation:
            'Enterprise systems require proactive alerting when the 99th percentile response time crosses SLA boundaries.',
          requiredSkills: ['Prometheus', 'PromQL', 'Grafana', 'SRE'],
          requiredTools: ['Prometheus server', 'Grafana dashboard', 'cURL generator'],
          instructions: [
            'Implement prometheus.NewHistogramVec measuring request duration in seconds with logarithmic buckets',
            'Expose /metrics endpoint on port 9090',
            'Write a PromQL expression: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))',
            'Verify alerting threshold fires when synthetic 500ms delay is injected',
          ],
          expectedOutput:
            'A live Grafana dashboard displaying P50, P90, and P99 latency with automated alert triggering.',
          checklist: [
            'Histogram buckets properly configured',
            'Metrics endpoint verified via curl',
            'PromQL alert expression validated',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'gco_s4',
        stageNumber: 4,
        title: 'Final Challenge: Production Architecture Defense',
        shortDescription: 'Submit architecture blueprint and defend your sampling rate and storage strategy.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  {
    id: 'proj_amazon_serverless_order',
    title: 'High-Throughput Serverless Order Processing & Event Engine',
    domain: 'Software Development',
    industryCategory: 'E-Commerce & Retail',
    companyName: 'Amazon',
    difficulty: 'Intermediate',
    estimatedDuration: '4 - 5 Weeks (30 hours)',
    description:
      'Design an event-driven order processing engine using AWS Lambda, DynamoDB Single-Table Design, and SQS FIFO queues with dead-letter queue resilience and idempotent transaction handling.',
    requiredSkills: ['Python', 'AWS', 'DynamoDB', 'Serverless', 'System Design'],
    recommendedCompanies: ['Amazon', 'Flipkart', 'Walmart', 'Shopify'],
    softwareRequirements: ['Python 3.11+', 'AWS CLI / LocalStack', 'Serverless Framework / SAM', 'pytest'],
    expectedOutput:
      'An automated event pipeline processing 1,000 orders/second with zero duplicate charges, automatic retry on transient failure, and sub-100ms processing latency.',
    descriptiveQuestionPrompt:
      'How does your order processing pipeline ensure idempotency when an upstream payment gateway retries a webhook notification? Detail your DynamoDB transaction lock strategy.',
    stages: [
      {
        id: 'aso_s1',
        stageNumber: 1,
        title: 'Event-Driven Architecture & DynamoDB Single-Table Design',
        shortDescription: 'Master partition keys, sort keys, and global secondary indexes for sub-millisecond query performance.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_coursera_aws_dev',
            title: 'AWS Certified Developer Associate Specialization',
            provider: 'Coursera',
            topic: 'DynamoDB & Event-Driven Serverless Workflows',
            skillCovered: 'AWS',
            level: 'Intermediate',
            estimatedDuration: '8 hours',
            url: 'https://www.coursera.org/specializations/aws-certified-developer-associate',
            isOfficial: true,
          },
          {
            id: 'res_nptel_cloud_arch',
            title: 'Cloud Computing and Distributed Systems by IIT Kharagpur',
            provider: 'NPTEL',
            topic: 'Eventual Consistency & NoSQL Scaling',
            skillCovered: 'System Design',
            level: 'Intermediate',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/106/105/106105167/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_aso_1_1',
            question: 'Why is DynamoDB `TransactWriteItems` critical during order placement and inventory deduction?',
            options: [
              'It automatically generates product recommendation embeddings',
              'It executes multiple write operations atomically with ACID guarantees, ensuring either both order record and inventory update succeed or neither does',
              'It reduces network egress charges to zero',
              'It compresses table data by 90% using zstd',
            ],
            correctAnswer: 1,
            explanation:
              'TransactWriteItems provides ACID atomicity across up to 100 items or 4MB of data, eliminating race conditions such as selling out-of-stock items.',
            topic: 'NoSQL Architecture',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'aso_s2',
        stageNumber: 2,
        title: 'Guided Task: Implement Idempotent SQS Consumer Lambda',
        shortDescription: 'Write a resilient consumer that verifies idempotency tokens before deducting inventory.',
        type: 'guided_task',
        xpReward: 250,
        task: {
          id: 'task_aso_idempotency',
          title: 'Build Idempotent Lambda Handler with Conditional Writes',
          objective: 'Guarantee that duplicate SQS messages do not trigger duplicate order fulfillments.',
          explanation:
            'Network timeouts frequently cause producers to retry messages. The receiver must use conditional writes (attribute_not_exists) to reject duplicate message processing.',
          requiredSkills: ['Python', 'boto3', 'Unit Testing'],
          requiredTools: ['LocalStack / AWS', 'Python', 'pytest'],
          instructions: [
            'Create a DynamoDB table with PK=ORDER#{orderId} and SK=METADATA',
            'Write a Lambda function in Python parsing SQS events',
            'Execute PutItem with ConditionExpression="attribute_not_exists(order_id)"',
            'Simulate sending the identical message twice and assert that second attempt returns ConditionalCheckFailedException gracefully',
          ],
          expectedOutput:
            'Passing pytest test suite demonstrating idempotency under duplicate delivery.',
          checklist: [
            'Conditional check expression implemented',
            'Dead letter queue redrive policy configured',
            'All unit tests passing',
          ],
          difficulty: 'Intermediate',
          xpReward: 250,
        },
      },
      {
        id: 'aso_s3',
        stageNumber: 3,
        title: 'Final Challenge: System Scalability & Cost Optimization',
        shortDescription: 'Defend your queue concurrency limits, provisioned concurrency vs on-demand billing, and failure modes.',
        type: 'final_challenge',
        xpReward: 350,
      },
    ],
  },
  {
    id: 'proj_microsoft_copilot_rag',
    title: 'Enterprise Copilot & Semantic Retrieval Engine (Hybrid RAG)',
    domain: 'Artificial Intelligence',
    industryCategory: 'AI & Enterprise Software',
    companyName: 'Microsoft',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks (35 hours)',
    description:
      'Build a high-precision enterprise document Q&A copilot using hybrid search (BM25 lexical + dense vector embeddings), reciprocal rank fusion (RRF), cross-encoder re-ranking, and hallucination guardrails.',
    requiredSkills: ['Python', 'Azure OpenAI', 'Vector Databases', 'LangChain', 'NLP'],
    recommendedCompanies: ['Microsoft', 'OpenAI', 'Google', 'Meta'],
    softwareRequirements: ['Python 3.11+', 'ChromaDB or Qdrant', 'HuggingFace Transformers', 'FastAPI'],
    expectedOutput:
      'A production-ready RAG microservice with sub-second retrieval accuracy over 10,000 PDF documents with source page citation and hallucination detection.',
    descriptiveQuestionPrompt:
      'How does your hybrid retrieval architecture balance semantic similarity with exact keyword matching for technical terminology? What metrics do you track to evaluate answer faithfulness?',
    stages: [
      {
        id: 'rag_s1',
        stageNumber: 1,
        title: 'Dense Embeddings, Chunking Strategies & Vector Spaces',
        shortDescription: 'Master semantic chunking, cosine distance, and high-dimensional vector search.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_coursera_nlp',
            title: 'Natural Language Processing with Attention Models',
            provider: 'Coursera',
            topic: 'Transformer Embeddings & Vector Similarity',
            skillCovered: 'NLP',
            level: 'Advanced',
            estimatedDuration: '8 hours',
            url: 'https://www.coursera.org/learn/attention-models-in-nlp',
            isOfficial: true,
          },
          {
            id: 'res_nptel_deep_nlp',
            title: 'Deep Learning for NLP by IIT Bombay',
            provider: 'NPTEL',
            topic: 'Dense Retrieval and Information Extraction',
            skillCovered: 'Artificial Intelligence',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/106/101/106101211/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_rag_1_1',
            question: 'Why does pure dense semantic embedding search sometimes fail on domain-specific acronyms like "ISO-26262-ASIL-D"?',
            options: [
              'Embeddings cannot represent numbers greater than 1,000',
              'Dense models map out-of-vocabulary technical codes to generic subword regions, whereas sparse BM25 excels at exact lexical matching',
              'Dense vector databases only store lowercase ASCII characters',
              'Cosine distance becomes negative for acronyms',
            ],
            correctAnswer: 1,
            explanation:
              'Dense embeddings capture high-level semantic meaning but often dilute exact codes. Hybrid search combines BM25 lexical precision with dense vector semantic depth using Reciprocal Rank Fusion.',
            topic: 'RAG Architecture',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'rag_s2',
        stageNumber: 2,
        title: 'Core Build: Reciprocal Rank Fusion & Cross-Encoder Re-Ranking',
        shortDescription: 'Combine BM25 and vector scores and re-rank top 5 candidates with cross-encoder.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_rag_pipeline',
          title: 'Implement Hybrid RAG Pipeline in Python',
          objective: 'Process multi-page enterprise PDFs, generate vector index, and verify citation groundedness.',
          explanation:
            'Load documents with semantic chunking, ingest into vector store, run parallel BM25 and vector queries, and compute RRF scores.',
          requiredSkills: ['Python', 'Vector DB', 'Sentence Transformers'],
          requiredTools: ['Python 3.11', 'FastAPI', 'ChromaDB'],
          instructions: [
            'Chunk documents with 512-token overlap window',
            'Generate dense embeddings using text-embedding-3-small or all-MiniLM-L6-v2',
            'Implement RRF algorithm: RRF_score = sum(1 / (60 + rank))',
            'Construct grounded prompt containing retrieved contexts and prompt LLM to cite document sources',
          ],
          expectedOutput:
            'A FastAPI endpoint returning verified answer with grounded confidence score and cited page numbers.',
          checklist: [
            'Document chunking with overlap verified',
            'Hybrid BM25 + dense search returning ranked documents',
            'Context injection prompt preventing hallucination',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'rag_s3',
        stageNumber: 3,
        title: 'Final Challenge: Defense of Context Window Optimization',
        shortDescription: 'Defend token economics, guardrails against prompt injection, and latency tradeoffs.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  {
    id: 'proj_nvidia_edge_vision',
    title: 'Real-Time Edge AI Multi-Camera Detection & DeepStream Pipeline',
    domain: 'Artificial Intelligence',
    industryCategory: 'Computer Vision & Semiconductors',
    companyName: 'NVIDIA',
    difficulty: 'Advanced',
    estimatedDuration: '5 - 6 Weeks (38 hours)',
    description:
      'Build a hardware-accelerated computer vision pipeline utilizing TensorRT FP16/INT8 model quantization, CUDA stream pipelining, and DeepStream SDK to track objects across multiple concurrent 1080p video feeds at 60 FPS.',
    requiredSkills: ['Python', 'CUDA', 'TensorRT', 'OpenCV', 'Deep Learning'],
    recommendedCompanies: ['NVIDIA', 'Apple', 'Qualcomm', 'Tesla'],
    softwareRequirements: ['Ubuntu Linux', 'CUDA Toolkit 12+', 'TensorRT', 'Python OpenCV', 'PyTorch'],
    expectedOutput:
      'A real-time inference engine achieving <12ms inference latency per frame on 4 simultaneous 1080p camera streams.',
    descriptiveQuestionPrompt:
      'How does INT8 quantization affect model accuracy and inference throughput in your vision pipeline? Describe your calibration strategy to prevent perceptual drift.',
    stages: [
      {
        id: 'nev_s1',
        stageNumber: 1,
        title: 'CUDA Memory Architecture & TensorRT Model Compilation',
        shortDescription: 'Master pinned memory, zero-copy buffers, and engine serialization.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_nvidia_dli',
            title: 'NVIDIA Deep Learning Institute: Fundamentals of Accelerated Computing',
            provider: 'Official Documentation',
            topic: 'CUDA Streams & GPU Kernel Optimization',
            skillCovered: 'CUDA',
            level: 'Advanced',
            estimatedDuration: '8 hours',
            url: 'https://www.nvidia.com/en-us/training/',
            isOfficial: true,
          },
          {
            id: 'res_nptel_gpu_comp',
            title: 'GPU Architectures and Programming by IIT Kharagpur',
            provider: 'NPTEL',
            topic: 'Shared Memory & Warp Divergence',
            skillCovered: 'Hardware Architecture',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/106/105/106105220/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_nev_1_1',
            question: 'What is the primary performance benefit of using CUDA Pinned (Page-Locked) Host Memory during frame transfer?',
            options: [
              'It encrypts video frames against HDMI sniffing',
              'It enables Direct Memory Access (DMA) hardware to transfer bytes directly between host RAM and GPU VRAM without CPU staging',
              'It automatically converts color spaces from YUV to RGB',
              'It downsamples video resolution to save bandwidth',
            ],
            correctAnswer: 1,
            explanation:
              'Pageable memory must first be copied to an internal OS buffer before GPU DMA can read it. Pinned memory bypasses this CPU copy, doubling transfer bandwidth.',
            topic: 'GPU Architecture',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'nev_s2',
        stageNumber: 2,
        title: 'Core Build: TensorRT Quantized Engine & Multi-Threaded Loop',
        shortDescription: 'Compile ONNX to TensorRT plan and run asynchronous batched inference.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_nev_inference',
          title: 'Implement Multi-Threaded Video Inference Loop in Python/C++',
          objective: 'Decouple video decoding, GPU inference, and tracking display across parallel threads.',
          explanation:
            'In multi-camera pipelines, disk/network decoding must run asynchronously to prevent stalling the GPU execution stream.',
          requiredSkills: ['Python', 'OpenCV', 'TensorRT'],
          requiredTools: ['TensorRT', 'Python', 'Webcam / Test Video'],
          instructions: [
            'Export YOLOv8 model to ONNX format',
            'Compile ONNX model to TensorRT FP16 engine with trtexec',
            'Create worker thread reading RTSP/video frames into a thread-safe ring buffer',
            'Execute asynchronous cudaStream inference and measure frame processing FPS',
          ],
          expectedOutput:
            'A sustained 60 FPS video stream with bounding boxes and track IDs rendered with <15ms end-to-end latency.',
          checklist: [
            'TensorRT engine built with FP16 enabled',
            'Producer-consumer queue decoupled',
            'FPS counter benchmarked and logged',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'nev_s3',
        stageNumber: 3,
        title: 'Final Challenge: Autonomous Edge Deployment Defense',
        shortDescription: 'Defend heat dissipation, edge power budgets (15W Jetson), and thermal throttling mitigations.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  {
    id: 'proj_tesla_can_telemetry',
    title: 'Autonomous Vehicle CAN Bus Telemetry & Predictive Safety System',
    domain: 'Embedded Systems',
    industryCategory: 'Automotive & Autonomous Systems',
    companyName: 'Tesla',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks (34 hours)',
    description:
      'Develop an automotive electronic control unit (ECU) telematics gateway in C++ that decodes high-speed CAN bus frames (500 kbps), filters sensor noise with a Kalman filter, and flags safety-critical anomalies.',
    requiredSkills: ['C++', 'CAN Protocol', 'Embedded Systems', 'Kalman Filter', 'Automotive'],
    recommendedCompanies: ['Tesla', 'Bosch', 'Tata Motors', 'Mercedes-Benz'],
    softwareRequirements: ['Ubuntu Linux', 'SocketCAN tools (can-utils)', 'vcan virtual CAN interface', 'C++17 compiler'],
    expectedOutput:
      'A deterministic Linux SocketCAN gateway parsing 2,000 CAN frames/sec with zero buffer overrun, logging real-time wheel speed differentials and battery cell temperatures.',
    descriptiveQuestionPrompt:
      'How does CAN bus non-destructive bitwise arbitration guarantee that safety-critical messages (e.g., emergency braking) take precedence over comfort telemetry without message collision?',
    stages: [
      {
        id: 'tct_s1',
        stageNumber: 1,
        title: 'Controller Area Network (CAN 2.0B) Physical & Data Link Layer',
        shortDescription: 'Master differential signaling (CAN_H, CAN_L), identifier arbitration, and CRC error framing.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_coursera_auto_sec',
            title: 'Automotive Embedded Systems and CAN Communication',
            provider: 'Coursera',
            topic: 'CAN Bus Protocols and Electronic Control Units',
            skillCovered: 'CAN Protocol',
            level: 'Advanced',
            estimatedDuration: '8 hours',
            url: 'https://www.coursera.org/learn/automotive-cybersecurity',
            isOfficial: true,
          },
          {
            id: 'res_nptel_mechatronics',
            title: 'Mechatronics & Automotive Sensors by IIT Roorkee',
            provider: 'NPTEL',
            topic: 'Vehicle Networks & Transducers',
            skillCovered: 'Embedded Systems',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/112/107/112107298/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_tct_1_1',
            question: 'On a high-speed CAN bus, which identifier has higher priority during simultaneous bus access?',
            options: [
              'The identifier with the higher numerical value (more 1s)',
              'The identifier with the lower numerical value (dominant 0 bits win arbitration over recessive 1s)',
              'The identifier with the longer payload size',
              'The message sent from the highest physical node address',
            ],
            correctAnswer: 1,
            explanation:
              'In CAN bitwise arbitration, logic 0 is dominant (drives bus differential voltage) and logic 1 is recessive. The lower numerical identifier asserts more 0s and wins arbitration without losing clock cycles.',
            topic: 'CAN Bus Protocol',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'tct_s2',
        stageNumber: 2,
        title: 'Core Build: SocketCAN Receiver & DBC Frame Decoder',
        shortDescription: 'Bind raw Linux CAN sockets, parse wheel speed telemetry, and trigger alerts on sensor deviation.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_tct_socketcan',
          title: 'Build High-Speed C++ SocketCAN Telemetry Reader',
          objective: 'Process virtual CAN traffic on vcan0 interface and compute real-time wheel speed differentials.',
          explanation:
            'Autonomous traction control systems require continuous comparison between left and right wheel encoder speeds to detect wheel slip.',
          requiredSkills: ['C++', 'Linux Sockets', 'Bit Manipulation'],
          requiredTools: ['g++', 'can-utils (cangen, candump)', 'Linux Terminal'],
          instructions: [
            'Set up virtual CAN interface: `sudo ip link add dev vcan0 type vcan && sudo ip link set up vcan0`',
            'Write C++ program opening `AF_CAN` socket with `CAN_RAW` protocol',
            'Decode 64-bit payload with endian conversion for WheelSpeedFrontLeft and WheelSpeedFrontRight',
            'Apply rolling exponential moving average filter and trigger safety flag if differential > 15%',
          ],
          expectedOutput:
            'A compiled C++ executable logging filtered vehicle metrics and zero dropped CAN frames under 1,000 msg/sec load.',
          checklist: [
            'SocketCAN interface bound successfully',
            'Endianness and scaling factor applied accurately',
            'Traction slip threshold test verified',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'tct_s3',
        stageNumber: 3,
        title: 'Final Challenge: Functional Safety (ISO 26262) Defense',
        shortDescription: 'Defend fail-safe operational modes, watchdog timer resets, and hardware fault injection tests.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  {
    id: 'proj_goldman_order_matching',
    title: 'High-Frequency Algorithmic Order Matching Engine',
    domain: 'Software Development',
    industryCategory: 'FinTech & Quantitative Finance',
    companyName: 'Goldman Sachs',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks (36 hours)',
    description:
      'Engineer a ultra-low-latency limit order book matching engine in modern C++ featuring lock-free ring buffers, cache-line aligned price levels, price-time priority (FIFO) matching, and microsecond order execution benchmarks.',
    requiredSkills: ['C++', 'Low-Latency Systems', 'Algorithms', 'Data Structures', 'Multithreading'],
    recommendedCompanies: ['Goldman Sachs', 'JPMorgan Chase', 'Morgan Stanley', 'Jane Street'],
    softwareRequirements: ['C++20 (GCC or Clang)', 'Linux with taskset / isolcpus', 'Google Benchmark', 'CMake'],
    expectedOutput:
      'A standalone matching engine executing over 500,000 order insertions, cancellations, and matches per second with P99 latency under 2.5 microseconds.',
    descriptiveQuestionPrompt:
      'How does memory layout and cache alignment impact order book matching speed? Explain your design choices to eliminate cache thrashing and false sharing across reader and writer threads.',
    stages: [
      {
        id: 'ome_s1',
        stageNumber: 1,
        title: 'Limit Order Book Mechanics & Cache Alignment',
        shortDescription: 'Master price-time priority, double-ended queues, and CPU L1/L2 cache line packing.',
        type: 'concept',
        xpReward: 150,
        learningResources: [
          {
            id: 'res_mit_algo_fin',
            title: 'Algorithms and Data Structures by MIT OpenCourseWare',
            provider: 'Official Documentation',
            topic: 'Advanced Priority Queues and Cache-Conscious Structures',
            skillCovered: 'Data Structures',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/',
            isOfficial: true,
          },
          {
            id: 'res_nptel_adv_ds',
            title: 'Advanced Data Structures by IIT Delhi',
            provider: 'NPTEL',
            topic: 'Red-Black Trees, B-Trees and Lock-Free Structures',
            skillCovered: 'Algorithms',
            level: 'Advanced',
            estimatedDuration: '10 hours',
            url: 'https://nptel.ac.in/courses/106/102/106102064/',
            isOfficial: true,
          },
        ],
        mcqs: [
          {
            id: 'mcq_ome_1_1',
            question: 'Why do high-frequency trading matching engines avoid allocating heap memory (`new` / `malloc`) during active order execution?',
            options: [
              'Heap memory cannot store 64-bit integer price ticks',
              'Heap allocation involves system calls and locks that induce unpredictable non-deterministic latency spikes up to several milliseconds',
              'Operating systems limit heap memory to 1MB per process',
              'Modern compilers do not support heap pointers in C++20',
            ],
            correctAnswer: 1,
            explanation:
              'Dynamic memory allocation invokes the glibc allocator which may take OS locks, cause page faults, or fragment memory. Low-latency engines pre-allocate fixed memory pools at startup.',
            topic: 'Low-Latency Architecture',
            difficulty: 'Advanced',
          },
        ],
      },
      {
        id: 'ome_s2',
        stageNumber: 2,
        title: 'Core Build: Lock-Free Price Level Book & Trade Matching',
        shortDescription: 'Implement Bids and Asks order queues with zero allocation during order book traversal.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_ome_engine',
          title: 'Build C++ Order Matching Engine with Microsecond Benchmark',
          objective: 'Match incoming market and limit orders according to strict price-time priority rules.',
          explanation:
            'When a Buy order has price >= Best Ask, immediately cross the spread, execute trades, and update remaining shares.',
          requiredSkills: ['C++', 'Data Structures', 'Benchmarking'],
          requiredTools: ['CMake', 'g++-12', 'perf / benchmark'],
          instructions: [
            'Create Order struct aligned to 64 bytes (`alignas(64)`)',
            'Implement PriceLevel linked-list storing orders at given price point',
            'Write `match_order(Order& incoming)` executing full and partial fills',
            'Write benchmark generating 100,000 random order operations and compute latency percentiles (P50, P90, P99)',
          ],
          expectedOutput:
            'A verified benchmark output demonstrating <3 microsecond mean match latency with zero memory leaks.',
          checklist: [
            'Order struct aligned to CPU cache line',
            'Partial fills and complete matches handled correctly',
            'P99 latency recorded and verified',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'ome_s3',
        stageNumber: 3,
        title: 'Final Challenge: Financial Integrity & Exchange Resilience',
        shortDescription: 'Defend market integrity, order cancellation race conditions, and deterministic replay auditing.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 7. APPLE: Real-Time Neural Audio DSP & On-Device Voice Isolation Engine
  {
    id: 'proj_apple_audio_dsp',
    title: 'Real-Time Neural Audio DSP & On-Device Voice Isolation Engine',
    companyName: 'Apple',
    domain: 'Artificial Intelligence',
    industryCategory: 'Product Company',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Engineer a real-time digital signal processing (DSP) and neural voice isolation pipeline modeled on CoreAudio and Apple Neural Engine. Filter environmental background noise in under 12ms round-trip latency.',
    requiredSkills: ['C++', 'Python', 'Digital Signal Processing', 'PyTorch', 'CoreAudio / WebAudio'],
    recommendedCompanies: ['Apple', 'Dolby Laboratories', 'Bose', 'Sennheiser', 'Sony'],
    softwareRequirements: ['C++20', 'CMake', 'PyTorch 2.2+', 'FFmpeg', 'PortAudio / Libsndfile'],
    expectedOutput:
      'Low-latency C++/Python audio processing pipeline with real-time spectrogram filtering, quantized neural network inference, and SNR benchmark report (>18dB SNR improvement).',
    descriptiveQuestionPrompt:
      'Explain how your audio processing pipeline balances circular buffer frame sizes (hop length vs FFT window size) to satisfy strict real-time latency (<15ms) while mitigating spectral smearing artifacts.',
    stages: [
      {
        id: 'apple_dsp_s1',
        stageNumber: 1,
        title: 'Fourier Transforms, STFT & Spectral Masking Foundations',
        shortDescription: 'Master Short-Time Fourier Transforms (STFT), circular ring buffers, and complex ratio masking.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_dsp_apple',
            title: 'Digital Signal Processing by IIT Kharagpur',
            provider: 'NPTEL',
            topic: 'Digital Signal Processing & Filter Design',
            skillCovered: 'Digital Signal Processing',
            level: 'Intermediate',
            estimatedDuration: '8 Weeks',
            url: 'https://nptel.ac.in/courses/117105101',
            isOfficial: true,
            institution: 'IIT Kharagpur',
            instructor: 'Prof. V.M. Gadre',
            syllabusHighlights: [
              'Discrete-Time Signals, Z-Transforms and Filter Banks',
              'Fast Fourier Transform (FFT) Decimation in Time & Frequency',
              'Short-Time Spectral Analysis and Windowing Functions (Hanning, Blackman)',
              'Real-Time Convolution and Circular Buffer Mechanics',
            ],
          },
          {
            id: 'res_coursera_audio_dsp',
            title: 'Audio Signal Processing for Music Applications',
            provider: 'Coursera',
            topic: 'Spectral Analysis & Real-time Synthesis',
            skillCovered: 'Audio Processing',
            level: 'Advanced',
            estimatedDuration: '5 Weeks',
            url: 'https://www.coursera.org/learn/audio-signal-processing',
            isOfficial: true,
            institution: 'Stanford University & Universitat Pompeu Fabra',
          },
        ],
        mcqs: [
          {
            id: 'mcq_apple_dsp_1',
            question: 'In real-time speech enhancement, what is the primary consequence of choosing a very large FFT window size (e.g., 2048 samples at 16kHz)?',
            options: [
              'Higher frequency resolution at the expense of increased algorithmic latency and poorer time resolution',
              'Zero latency and infinite frequency resolution',
              'Automatic phase cancellation without computational overhead',
              'Reduction in sample rate down to telephone quality',
            ],
            correctAnswer: 0,
            explanation:
              'Window size represents a fundamental Heisenberg-Gabor trade-off: larger windows enhance frequency resolution but increase algorithmic buffering latency (2048 samples @ 16kHz = 128ms latency).',
            topic: 'STFT Time-Frequency Trade-offs',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'apple_dsp_s2',
        stageNumber: 2,
        title: 'Core Build: Circular Audio Ring Buffer & Quantized Noise Supressor',
        shortDescription: 'Implement lock-free circular audio buffer and run quantized deep complex U-Net inference.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_apple_dsp_impl',
          title: 'Implement C++ Real-Time Ring Buffer & Neural Masking Filter',
          objective:
            'Build a lock-free single-producer single-consumer circular audio buffer and stream 512-sample audio blocks through an ONNX/PyTorch quantized voice isolation model.',
          explanation:
            'Production audio applications cannot tolerate lock contention or dynamic heap allocations inside the high-priority real-time audio callback. Memory must be pre-allocated in static ring buffers.',
          requiredSkills: ['C++', 'Digital Signal Processing', 'ONNX Runtime', 'Memory Management'],
          requiredTools: ['Clang/GCC', 'CMake', 'Valgrind', 'Audacity / Sox'],
          instructions: [
            'Create a LockFreeAudioRingBuffer class with atomic read/write head pointers',
            'Write overlap-add (OLA) STFT analysis and synthesis routines with Hanning windowing',
            'Integrate quantized speech enhancement ONNX model to generate a spectral suppression mask',
            'Benchmark round-trip processing time and verify zero audio buffer underruns',
          ],
          expectedOutput:
            'C++ executable streaming live mic/file audio, producing crystal clear voice output with verified latency under 12ms.',
          checklist: [
            'Lock-free audio ring buffer implemented with atomic memory ordering',
            'STFT and inverse STFT match original signal within -90dB reconstruction error',
            'Quantized inference executes in <4ms per 32ms hop frame',
            'Processed audio demonstrates >15dB signal-to-noise ratio improvement',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'apple_dsp_s3',
        stageNumber: 3,
        title: 'Final Challenge: Acoustic Echo & Latency Budget Defense',
        shortDescription: 'Defend acoustic echo cancellation convergence, double-talk detection, and CPU thermal throttling resilience.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 8. NETFLIX: Global CDN Dynamic Route Optimizer & Adaptive Bitrate Engine
  {
    id: 'proj_netflix_cdn_abr',
    title: 'Global CDN Dynamic Route Optimizer & Adaptive Bitrate Streaming Engine',
    companyName: 'Netflix',
    domain: 'Cloud Computing',
    industryCategory: 'Cloud Infrastructure',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Architect a distributed CDN edge routing proxy and adaptive bitrate (ABR) controller modeled on Netflix Open Connect. Route video segments based on real-time BGP telemetry and network congestion.',
    requiredSkills: ['Go', 'Distributed Systems', 'HTTP/3 & QUIC', 'Video Streaming', 'Networking'],
    recommendedCompanies: ['Netflix', 'Cloudflare', 'Fastly', 'Akamai', 'YouTube'],
    softwareRequirements: ['Go 1.22+', 'Docker Compose', 'Wireshark', 'FFmpeg', 'HLS / MPEG-DASH specs'],
    expectedOutput:
      'Edge CDN proxy in Go supporting BOLA/BBA adaptive bitrate selection, dynamic upstream failover, and P99 video segment delivery <60ms.',
    descriptiveQuestionPrompt:
      'Analyze how your adaptive bitrate algorithm prevents buffer underrun stalls while avoiding unnecessary resolution oscillation during volatile cellular network throttling.',
    stages: [
      {
        id: 'nflx_s1',
        stageNumber: 1,
        title: 'MPEG-DASH/HLS Chunking & BBA-2 Bitrate Adaptation Models',
        shortDescription: 'Master chunked media delivery, manifest parsing, and buffer-based bitrate adaptation algorithms.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_computernetworks_nflx',
            title: 'Computer Networks and Internet Protocol by IIT Kharagpur',
            provider: 'NPTEL',
            topic: 'Congestion Control, TCP/QUIC & Media Streaming',
            skillCovered: 'Networking',
            level: 'Intermediate',
            estimatedDuration: '12 Weeks',
            url: 'https://nptel.ac.in/courses/106105183',
            isOfficial: true,
            institution: 'IIT Kharagpur',
            instructor: 'Prof. Soumya Kanti Ghosh',
            syllabusHighlights: [
              'Transport Layer Protocols: TCP Reno, Cubic, BBR and QUIC/HTTP3',
              'Content Distribution Networks (CDNs) & Anycast Routing Architecture',
              'Quality of Service (QoS) in Multimedia Streaming Networks',
            ],
          },
        ],
        mcqs: [
          {
            id: 'mcq_nflx_1',
            question: 'Why do modern video players utilize Buffer-Based Adaptation (BBA) rather than purely throughput-based rate estimation?',
            options: [
              'Throughput estimation is prone to TCP slow-start noise and rapid chunk download spikes, causing rapid video quality flipping',
              'Throughput estimation consumes too much client memory on mobile devices',
              'BBA eliminates the need for video compression codecs entirely',
              'BBA requires no feedback loop from the player buffer',
            ],
            correctAnswer: 0,
            explanation:
              'Buffer-Based Adaptation decouples bitrate switching from noisy short-term throughput variations, choosing video quality purely based on current playback reservoir margin.',
            topic: 'Adaptive Bitrate Algorithms',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'nflx_s2',
        stageNumber: 2,
        title: 'Core Build: High-Throughput Edge Media Proxy in Go',
        shortDescription: 'Build an asynchronous Go proxy caching HLS video chunks with health checking and BBR congestion telemetry.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_nflx_proxy',
          title: 'Build Go Edge Media Cache Proxy with BOLA Algorithm',
          objective:
            'Implement a reverse proxy in Go that caches media fragments in LRU memory and dynamically steers client requests to the lowest-latency origin node.',
          explanation:
            'Open Connect appliance architectures leverage tiered memory and SSD caches with non-blocking epoll/kqueue event loops to stream terabits per second.',
          requiredSkills: ['Go', 'Concurrency', 'HTTP Proxying', 'Caching'],
          requiredTools: ['Go Compiler', 'Docker', 'Curl', 'Apache Bench'],
          instructions: [
            'Construct an LRU memory cache with thread-safe atomic read locks',
            'Implement round-robin and latency-weighted upstream origin selection with automatic circuit breakers',
            'Simulate network throttle drops (5Mbps -> 800Kbps) and verify player seamlessly downscales without freeze frames',
            'Record Prometheus metrics for cache hit ratio, origin round-trip time, and byte egress rate',
          ],
          expectedOutput:
            'A scalable Go media edge server caching segments and achieving >92% cache hit ratio under multi-client playback tests.',
          checklist: [
            'LRU Cache handles segment eviction smoothly under memory pressure',
            'Circuit breaker trips origin offline after 3 consecutive 5xx errors or timeouts',
            'Dynamic ABR client switches bitrate within 1 chunk window during network throttling',
            'Passing benchmark: 5,000 req/sec sustained with P99 < 15ms',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'nflx_s3',
        stageNumber: 3,
        title: 'Final Challenge: Global BGP Anycast Routing & Origin Failover Defense',
        shortDescription: 'Defend origin regional blackout survival, cache stampede prevention, and zero-stall stream continuity.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 9. UBER: Distributed H3 Geospatial Trip Dispatcher & Surge Engine
  {
    id: 'proj_uber_h3_dispatch',
    title: 'Distributed H3 Geospatial Trip Dispatcher & Surge Pricing Telemetry',
    companyName: 'Uber',
    domain: 'Software Development',
    industryCategory: 'Software',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Build a distributed real-time ride matching and surge pricing engine using Uber H3 hexagonal spatial indexing, Redis geospatial pub/sub, and Hungarian algorithm bipartite driver assignment.',
    requiredSkills: ['Python', 'TypeScript', 'Uber H3', 'Redis', 'Graph Algorithms', 'Docker'],
    recommendedCompanies: ['Uber', 'Lyft', 'DoorDash', 'Grab', 'Zomato'],
    softwareRequirements: ['Python 3.11', 'Redis 7.2+', 'PostGIS / PostgreSQL', 'H3-py', 'NetworkX'],
    expectedOutput:
      'Real-time geospatial dispatch service allocating drivers to riders inside 100ms using H3 hex resolution index and bipartite graph optimization.',
    descriptiveQuestionPrompt:
      'Describe how your dispatch service handles geospatial boundary queries using H3 hexagonal hierarchical coordinates compared to traditional latitude/longitude bounding box polygon queries.',
    stages: [
      {
        id: 'uber_s1',
        stageNumber: 1,
        title: 'H3 Spatial Hierarchy, Geohashes & Bipartite Matching Foundations',
        shortDescription: 'Learn hexagonal discretization, H3 resolution levels, k-ring neighbor lookups, and minimum weight bipartite matching.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_spatial_uber',
            title: 'Design and Analysis of Algorithms by IIT Madras',
            provider: 'NPTEL',
            topic: 'Graph Algorithms, Bipartite Matching & Network Flow',
            skillCovered: 'Algorithms',
            level: 'Advanced',
            estimatedDuration: '8 Weeks',
            url: 'https://nptel.ac.in/courses/106106131',
            isOfficial: true,
            institution: 'IIT Madras',
            instructor: 'Prof. Madhavan Mukund',
            syllabusHighlights: [
              'Shortest Paths, Dijkstra, and A* Search on Road Networks',
              'Bipartite Graph Matching and Maximum Flow Min-Cut Theorem',
              'Geospatial Indexing and Quadtree / R-Tree Spatial Lookups',
            ],
          },
        ],
        mcqs: [
          {
            id: 'mcq_uber_1',
            question: 'Why did Uber design the H3 spatial index using hexagons rather than squares or triangles?',
            options: [
              'All neighboring cells share an identical center-to-center distance, minimizing directional distortion in radius searches',
              'Hexagons consume 50% fewer bytes when stored in 64-bit integer registers',
              'Square coordinate grids cannot represent curved roads',
              'Hexagons completely eliminate the need for latitude and longitude coordinates',
            ],
            correctAnswer: 0,
            explanation:
              'Hexagons have only one distance between adjacent centers (unlike squares where diagonal neighbors are √2 further away), eliminating directional bias in routing and surge calculations.',
            topic: 'Hexagonal Spatial Indexing',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'uber_s2',
        stageNumber: 2,
        title: 'Core Build: Redis Geohash Telemetry & Batch Bipartite Matcher',
        shortDescription: 'Implement 5-second batch window driver allocation and H3 k-ring surge density estimation.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_uber_dispatch',
          title: 'Implement Batch Ride Dispatch & Dynamic Surge Calculator',
          objective:
            'Build a microservice that indexes simulated driver GPS locations into H3 index strings (Resolution 8), aggregates supply/demand per hexagon, and matches rides via Hungarian algorithm.',
          explanation:
            'Matching riders greedy-one-by-one results in sub-optimal pickups. Modern dispatch engines collect ride requests over a short 3-5 second batch window and perform global optimization.',
          requiredSkills: ['Python', 'H3-py', 'Redis', 'Scipy / Hungarian Matching'],
          requiredTools: ['Python 3', 'Redis', 'Pytest', 'Docker'],
          instructions: [
            'Ingest driver telemetry stream and map GPS coordinates into H3 resolution 8 cells',
            'Compute dynamic surge multipliers per hex based on (Demand / Supply) with exponential smoothing',
            'Implement Kuhn-Munkres (Hungarian algorithm) to match batches of 50 riders with nearest 50 drivers minimizing total ETA',
            'Validate that driver reassignment race conditions are prevented using Redis distributed locks',
          ],
          expectedOutput:
            'Fully functional dispatch pipeline matching riders with drivers and publishing live geospatial surge map data.',
          checklist: [
            'H3 spatial indexing accurately groups drivers within resolution 8 (~460m radius)',
            'Batch matching completes in <45ms for 100 simultaneous requests',
            'Surge multipliers update continuously based on real-time supply deficit',
            'Redis distributed locks ensure zero double-assigned drivers',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'uber_s3',
        stageNumber: 3,
        title: 'Final Challenge: High Concurrency Dispatch & Driver Churn Resilience',
        shortDescription: 'Defend flash mob surges, GPS spoofing detection, and distributed consistency during Redis partition failures.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 10. META: Distributed Social Graph Indexing & Graph Neural Network (GNN)
  {
    id: 'proj_meta_gnn_graph',
    title: 'Distributed Social Graph Indexing & Real-Time Graph Neural Network Engine',
    companyName: 'Meta',
    domain: 'Artificial Intelligence',
    industryCategory: 'AI & Enterprise Software',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Develop a distributed billion-edge social graph storage and Graph Convolutional Network (GCN / GraphSAGE) recommendation system modeled on Meta TAO and PyTorch Geometric.',
    requiredSkills: ['Python', 'PyTorch Geometric', 'Distributed Systems', 'C++', 'Graph DB / RocksDB'],
    recommendedCompanies: ['Meta', 'LinkedIn', 'Twitter / X', 'Pinterest', 'Neo4j'],
    softwareRequirements: ['Python 3.11', 'PyTorch 2.2', 'PyTorch Geometric (PyG)', 'RocksDB', 'Redis'],
    expectedOutput:
      'High-throughput graph indexing engine with node embedding inference pipeline predicting friend/community connections with >88% ROC-AUC.',
    descriptiveQuestionPrompt:
      'Explain how your GraphSAGE neighborhood sampling strategy bounds memory consumption during message passing across high-degree power-law "celebrity" nodes.',
    stages: [
      {
        id: 'meta_s1',
        stageNumber: 1,
        title: 'Graph Theory, Adjacency Matrices & Spatial Message Passing',
        shortDescription: 'Master graph representation, adjacency list cache partitioning, and spatial message passing neural networks.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_graph_meta',
            title: 'Graph Theory and Applications by IIT Kanpur',
            provider: 'NPTEL',
            topic: 'Graph Representation & Spectral Graph Theory',
            skillCovered: 'Data Structures & Algorithms',
            level: 'Intermediate',
            estimatedDuration: '8 Weeks',
            url: 'https://nptel.ac.in/courses/111104130',
            isOfficial: true,
            institution: 'IIT Kanpur',
            instructor: 'Prof. Soumen Maity',
          },
        ],
        mcqs: [
          {
            id: 'mcq_meta_1',
            question: 'What is the primary advantage of inductive graph representation learners like GraphSAGE over transductive models like GCN?',
            options: [
              'GraphSAGE can generate embeddings for unseen nodes during inference by learning neighborhood aggregation functions',
              'GraphSAGE eliminates the need for edge weights or node features',
              'GraphSAGE requires storing the full adjacency matrix in GPU memory',
              'GraphSAGE only works on bipartite graphs',
            ],
            correctAnswer: 0,
            explanation:
              'GraphSAGE learns generalizable aggregation functions over local neighborhoods, allowing it to predict connections for newly registered users without retraining on the entire graph.',
            topic: 'Graph Neural Networks',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'meta_s2',
        stageNumber: 2,
        title: 'Core Build: RocksDB Graph Store & 2-Hop GraphSAGE Predictor',
        shortDescription: 'Construct key-value adjacency store and train a 2-hop neighborhood aggregator in PyTorch Geometric.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_meta_gnn',
          title: 'Build Distributed Adjacency Store & PyG Recommendation Model',
          objective:
            'Implement a compressed adjacency list index in RocksDB and train an inductive GraphSAGE link prediction model on a social network dataset.',
          explanation:
            'Real-world social graphs follow a power-law distribution. A naive full-neighborhood aggregation causes exponential neighbor explosion ("supernodes"). Local sampling is critical.',
          requiredSkills: ['Python', 'PyTorch Geometric', 'RocksDB / SQLite', 'Link Prediction'],
          requiredTools: ['PyTorch', 'NetworkX', 'Conda / Pip', 'CUDA'],
          instructions: [
            'Store node adjacency lists in serialized binary format inside embedded key-value storage',
            'Implement uniform 2-hop neighborhood sampling with bounds of k1=25, k2=10 neighbors',
            'Train a 2-layer GraphSAGE link prediction network with negative edge sampling and cosine similarity readout',
            'Evaluate link prediction accuracy on validation holdout set achieving >85% ROC-AUC',
          ],
          expectedOutput:
            'End-to-end graph engine serving real-time "People You May Know" recommendation candidates in under 35ms per query.',
          checklist: [
            'Adjacency lookup latency P99 < 5ms for 100,000+ edge graph',
            'Neighborhood sampling effectively caps GPU memory consumption during forward pass',
            'Link prediction validation ROC-AUC exceeds 85%',
            'API endpoint accepts user ID and outputs top-10 recommended social connections',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'meta_s3',
        stageNumber: 3,
        title: 'Final Challenge: Social Graph Partitioning & Cache Invalidation Defense',
        shortDescription: 'Defend distributed graph partitioning across clusters and real-time edge invalidation consistency.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 11. ISRO / DRDO: Satellite Telemetry Frame Decoder & Orbital Ephemeris Predictor
  {
    id: 'proj_isro_satellite_telemetry',
    title: 'Satellite Telemetry Frame Synchronizer & Orbital Ephemeris Predictor',
    companyName: 'ISRO / DRDO',
    domain: 'Aerospace',
    industryCategory: 'Aerospace',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Build a mission-critical CCSDS telemetry frame synchronizer, Reed-Solomon error correction decoder, and SGP4 orbital propagator modeled on Indian space and defense ground control systems.',
    requiredSkills: ['C++', 'Python', 'CCSDS Standards', 'Orbital Mechanics', 'Signal Processing'],
    recommendedCompanies: ['ISRO', 'DRDO', 'HAL', 'Bharat Electronics (BEL)', 'Astra Microwave'],
    softwareRequirements: ['C++17', 'Python 3.11', 'Skyfield / SGP4', 'Gnuplot', 'CMake'],
    expectedOutput:
      'High-reliability telemetry ground station pipeline decoding binary satellite downlink packets, correcting bit errors, and computing live ground-track coordinates.',
    descriptiveQuestionPrompt:
      'Explain how your telemetry synchronizer detects the CCSDS 32-bit Attached Sync Marker (ASM) across noisy downlinks with variable bit error rates without dropping entire payload frames.',
    stages: [
      {
        id: 'isro_s1',
        stageNumber: 1,
        title: 'CCSDS Telemetry Standards, Reed-Solomon Code & Orbital Mechanics',
        shortDescription: 'Study CCSDS 131.0-B packet telemetry, Forward Error Correction (FEC), and Keplerian orbital elements.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_aerospace_isro',
            title: 'Space Flight Mechanics by IIT Madras',
            provider: 'NPTEL',
            topic: 'Keplerian Orbits, Two-Line Element Sets & Perturbations',
            skillCovered: 'Aerospace Engineering',
            level: 'Advanced',
            estimatedDuration: '12 Weeks',
            url: 'https://nptel.ac.in/courses/101104062',
            isOfficial: true,
            institution: 'IIT Madras',
            instructor: 'Prof. M. Ramakrishna',
            syllabusHighlights: [
              'Two-Body Problem and Orbital Conic Sections',
              'Keplerian Elements (Inclination, Right Ascension of Ascending Node, Eccentricity)',
              'Satellite Tracking, Ground Pass Scheduling & Elevation Angles',
            ],
          },
        ],
        mcqs: [
          {
            id: 'mcq_isro_1',
            question: 'What is the purpose of the 32-bit Attached Sync Marker (0x1ACFFC1D) in CCSDS Telemetry Transfer Frames?',
            options: [
              'To delimit transfer frame boundaries in continuous serial bit streams received from space downlinks',
              'To encrypt the payload for military confidentiality',
              'To indicate the battery voltage of the satellite',
              'To compress the sensor telemetry data by 50%',
            ],
            correctAnswer: 0,
            explanation:
              'The 32-bit ASM (0x1ACFFC1D) provides a known autocorrelation sequence, allowing ground station correlators to identify exact frame boundaries even amidst channel bit slips.',
            topic: 'CCSDS Telemetry Architecture',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'isro_s2',
        stageNumber: 2,
        title: 'Core Build: Bit-Slip Correlator & SGP4 Ground Track Visualizer',
        shortDescription: 'Implement bitstream ASM correlator and predict satellite sub-satellite points using real TLE data.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_isro_telemetry',
          title: 'Implement C++ Telemetry Decoder & Python SGP4 Propagator',
          objective:
            'Build an automated telemetry receiver that parses raw byte streams, detects Attached Sync Markers with Hamming tolerance, and computes orbital latitude/longitude coordinates.',
          explanation:
            'Deep space and low-earth orbit communications suffer from Doppler shifts, atmospheric attenuation, and cosmic ray bit flips. Robust error correction and state recovery are mandatory.',
          requiredSkills: ['C++', 'Python', 'Signal Processing', 'CCSDS'],
          requiredTools: ['Clang/GCC', 'Python', 'Jupyter / Matplotlib', 'Git'],
          instructions: [
            'Implement a sliding window correlator searching for ASM with configurable Hamming distance threshold (up to 3 bit flips)',
            'Extract packet headers (Virtual Channel ID, Master Channel Frame Count, Packet Length)',
            'Implement Reed-Solomon (255, 223) decoding to correct up to 16 corrupted bytes per frame block',
            'Integrate SGP4 model to ingest Two-Line Element (TLE) datasets and plot ground footprint on world coordinates',
          ],
          expectedOutput:
            'Verified telemetry parser decoding simulated satellite pass data with zero unhandled framing exceptions and accurate orbital tracks.',
          checklist: [
            'Correlator locks on ASM with 0 dropped frames under 10^-3 bit error rate',
            'Reed-Solomon decoder successfully repairs injected single and burst byte errors',
            'SGP4 propagator outputs latitude, longitude, and altitude matching NASA JPL ephemeris within 100 meters',
            'Decoded telemetry parameters (temperature, voltage, attitude quaternion) displayed in clean terminal dashboard',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'isro_s3',
        stageNumber: 3,
        title: 'Final Challenge: Mission Safety & Redundant Ground Telecommand Defense',
        shortDescription: 'Defend command authentication, bitstream replay protection, and ground station handover continuity.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
  // 12. STRIPE: Idempotent Distributed Payment Gateway & Fraud Risk Scorer
  {
    id: 'proj_stripe_payment_engine',
    title: 'Idempotent Distributed Payment Gateway & Transaction Anomaly Risk Engine',
    companyName: 'Stripe',
    domain: 'FinTech',
    industryCategory: 'FinTech & Quantitative Finance',
    difficulty: 'Advanced',
    estimatedDuration: '4 - 6 Weeks',
    description:
      'Engineer an idempotent transaction processing pipeline and real-time fraud risk scoring engine modeled on Stripe. Guarantee exactly-once payment processing under network retries and distributed database latency.',
    requiredSkills: ['TypeScript', 'Node.js / Go', 'PostgreSQL', 'Redis', 'Cryptography & HMAC', 'Kafka'],
    recommendedCompanies: ['Stripe', 'Razorpay', 'Square / Block', 'PayPal', 'PhonePe'],
    softwareRequirements: ['Node.js 20+', 'PostgreSQL 16', 'Redis', 'Docker Compose', 'Jest'],
    expectedOutput:
      'Production payment API with cryptographic idempotency keys, dual-entry accounting ledger balance verification, and real-time fraud heuristics engine (<25ms response).',
    descriptiveQuestionPrompt:
      'Demonstrate how your idempotency engine utilizes atomic database transactions and distributed locks to prevent duplicate charge deductions during concurrent client retry requests.',
    stages: [
      {
        id: 'stripe_s1',
        stageNumber: 1,
        title: 'Distributed Transactions, Two-Phase Commit & Dual-Entry Ledgering',
        shortDescription: 'Master idempotency keys, dual-entry immutable ledger accounting, and ACID transaction isolation levels.',
        type: 'concept',
        xpReward: 200,
        learningResources: [
          {
            id: 'res_nptel_dbms_stripe',
            title: 'Database Management Systems by IIT Kharagpur',
            provider: 'NPTEL',
            topic: 'Transaction Concurrency, Two-Phase Locking & ACID',
            skillCovered: 'Database Systems',
            level: 'Intermediate',
            estimatedDuration: '8 Weeks',
            url: 'https://nptel.ac.in/courses/106105175',
            isOfficial: true,
            institution: 'IIT Kharagpur',
            instructor: 'Prof. Partha Pratim Das',
            syllabusHighlights: [
              'ACID Properties and Serializable Isolation Levels',
              'Deadlock Detection, Prevention & Two-Phase Locking (2PL)',
              'Write-Ahead Logging (WAL) and Crash Recovery Protocols',
            ],
          },
        ],
        mcqs: [
          {
            id: 'mcq_stripe_1',
            question: 'What is the primary danger if a payment API lacks idempotency key enforcement on POST /charges requests?',
            options: [
              'A network timeout causing an automatic client retry will bill the customer account multiple times for a single order',
              'The transaction will permanently deadlock the database server',
              'The payment gateway will convert the currency to Bitcoin automatically',
              'The HTTP connection will drop the TLS encryption layer',
            ],
            correctAnswer: 0,
            explanation:
              'In distributed networks, requests can succeed at the server while the response is lost in transit. Retrying without idempotency keys risks duplicate debits and serious regulatory violations.',
            topic: 'Idempotency in Financial APIs',
            difficulty: 'Intermediate',
          },
        ],
      },
      {
        id: 'stripe_s2',
        stageNumber: 2,
        title: 'Core Build: Idempotency Key Lock Engine & Dual-Entry Ledger in Node/PostgreSQL',
        shortDescription: 'Build database-backed idempotency middleware and transactional dual-entry balance transfer.',
        type: 'core_build',
        xpReward: 350,
        task: {
          id: 'task_stripe_payment',
          title: 'Implement Idempotent Payment Handler with Dual-Entry Ledger',
          objective:
            'Create an Express/Fastify service that intercepts Idempotency-Key headers, ensures exactly-once execution via PostgreSQL advisory locks, and updates debit/credit ledger records.',
          explanation:
            'Financial systems must never use single-column floating point balances. Every balance change must be recorded as matching debit and credit entries in an immutable ledger table.',
          requiredSkills: ['TypeScript', 'PostgreSQL', 'Redis', 'API Security'],
          requiredTools: ['Node.js', 'PostgreSQL', 'Docker', 'Postman / Curl'],
          instructions: [
            'Implement IdempotencyMiddleware checking Redis/Postgres for existing keys with status (STARTED, COMPLETED, FAILED)',
            'Wrap ledger updates in SERIALIZABLE PostgreSQL transactions ensuring sum(debits) === sum(credits)',
            'Implement real-time fraud rules (e.g. velocity limits: >3 transactions in 60 seconds from same IP/card flag for review)',
            'Execute concurrent curl bombardment testing and verify that duplicate requests return the identical original charge response',
          ],
          expectedOutput:
            'Hardened payment gateway microservice with 100% idempotency verification under concurrent race condition stress tests.',
          checklist: [
            'Idempotency key checks prevent duplicate charging under 20 concurrent requests with same key',
            'Dual-entry ledger enforces balanced debits and credits across all accounts',
            'Fraud anomaly detector flags rapid transaction bursts and velocity spikes',
            'Passing automated test suite with full edge-case coverage (timeouts, rollbacks, concurrent retries)',
          ],
          difficulty: 'Advanced',
          xpReward: 350,
        },
      },
      {
        id: 'stripe_s3',
        stageNumber: 3,
        title: 'Final Challenge: PCI-DSS Compliance & Distributed Reconciliation Defense',
        shortDescription: 'Defend zero data loss during cloud database failover and end-of-day bank settlement reconciliation.',
        type: 'final_challenge',
        xpReward: 400,
      },
    ],
  },
];
